export const AUTHENTICATE = "AUTHENTICATE";
export const UNAUTHENTICATE = "UNAUTHENTICATE";
export const SET_USERS = "SET_USERS";
export const DELETE_USER = "DELETE_USER";
export const TOGGLE_SHOW_FOLLOWS = "SHOW_FOLLOWS";
export const SHOW_BY_NAME_REQUEST = "SHOW_BY_NAME_REQUEST";
export const TOGGLE_FOLLOW_USER = "TOGGLE_FOLLOW_USER";
export const SET_IS_FETCHING = "SET_IS_FETCHING";