export {Home} from './Home/Home'
export {About} from './About/About'
export {Landing} from './Landing/Landing'
export {default as LogIn} from './LogIn/LogIn'
export {default as LogOut} from './LogOut/LogOut'
export {default as Users} from './Users/Users'
export {default as UserPage} from './UserPage/UserPage'
export {default as NotFound} from './NotFound/NotFound'